const menuSeed = [
  {
    nome: 'Hambúrguer',
    categoria: 'Lanches',
    preco: 28.9,
    precoComDesconto: null,
    descricao: 'Pão brioche, carne artesanal, queijo e molho da casa.',
    imagem: 'meatburger.webp',
    disponivel: true,
  },
  {
    nome: 'Batata Frita',
    categoria: 'Lanches',
    preco: 18.9,
    precoComDesconto: null,
    descricao: 'Porção crocante com sal fino e acompanhamento especial.',
    imagem: 'fries.webp',
    disponivel: true,
  },
  {
    nome: 'Coxinha',
    categoria: 'Lanches',
    preco: 8.5,
    precoComDesconto: null,
    descricao: 'Massa cremosa com recheio de frango temperado.',
    imagem: 'coxinha.webp',
    disponivel: true,
  },
  {
    nome: 'Hot Dog',
    categoria: 'Lanches',
    preco: 16.9,
    precoComDesconto: null,
    descricao: 'Salsicha, molho, batata palha e complementos tradicionais.',
    imagem: 'hotdog.webp',
    disponivel: true,
  },
  {
    nome: 'Caldeirada',
    categoria: 'Pratos principais',
    preco: 54.9,
    precoComDesconto: null,
    descricao: 'Peixe cozido com legumes, ervas e caldo encorpado.',
    imagem: 'fishstew.webp',
    disponivel: true,
  },
  {
    nome: 'Macarrão Frito',
    categoria: 'Pratos principais',
    preco: 32.9,
    precoComDesconto: null,
    descricao: 'Massa salteada com vegetais, molho oriental e proteína.',
    imagem: 'friednoodle.webp',
    disponivel: true,
  },
  {
    nome: 'Frango à Parmegiana',
    categoria: 'Pratos principais',
    preco: 42.9,
    precoComDesconto: null,
    descricao: 'Frango empanado, molho de tomate, queijo e arroz branco.',
    imagem: 'frangoparmegiana.webp',
    disponivel: true,
  },
  {
    nome: 'Feijoada',
    categoria: 'Pratos principais',
    preco: 39.9,
    precoComDesconto: null,
    descricao: 'Feijão preto, carnes selecionadas e acompanhamentos.',
    imagem: 'feijoada.webp',
    disponivel: true,
  },
  {
    nome: 'Suco',
    categoria: 'Bebidas',
    preco: 9.9,
    precoComDesconto: null,
    descricao: 'Suco natural preparado na hora.',
    imagem: 'juicesyrup.webp',
    disponivel: true,
    tipo: 'com_acompanhamento',
    gruposOpcoes: [{
      nome: 'Sabor',
      tipo: 'unica',
      obrigatorio: true,
      permiteQuantidade: false,
      opcoes: [
        { nome: 'Maracujá', precoAdicional: 0 },
        { nome: 'Uva', precoAdicional: 4 },
        { nome: 'Morango', precoAdicional: 3 },
        { nome: 'Laranja', precoAdicional: 5 },
      ],
    }],
  },
  {
    nome: 'Refrigerante',
    categoria: 'Bebidas',
    preco: 7.5,
    precoComDesconto: null,
    descricao: 'Lata gelada de refrigerante.',
    imagem: 'soda.webp',
    disponivel: true,
    tipo: 'com_acompanhamento',
    gruposOpcoes: [{
      nome: 'Sabor',
      tipo: 'unica',
      obrigatorio: true,
      permiteQuantidade: false,
      opcoes: [
        { nome: 'Guaraná Antarctica', precoAdicional: 0 },
        { nome: 'Coca-Cola', precoAdicional: 0 },
      ],
    }],
  },
  {
    nome: 'Limonada',
    categoria: 'Bebidas',
    preco: 8.9,
    precoComDesconto: null,
    descricao: 'Limonada gelada com toque cítrico equilibrado.',
    imagem: 'lemonade.webp',
    disponivel: true,
  },
  {
    nome: 'Milkshake',
    categoria: 'Bebidas',
    preco: 18.9,
    precoComDesconto: null,
    descricao: 'Milkshake cremoso de morango ou chocolate. Escolha 400 ml ou 700 ml.',
    imagem: 'milkshake.webp',
    disponivel: true,
    tipo: 'com_acompanhamento',
    gruposOpcoes: [
      {
        nome: 'Sabor',
        tipo: 'unica',
        obrigatorio: true,
        permiteQuantidade: false,
        opcoes: [
          { nome: 'Morango', precoAdicional: 0 },
          { nome: 'Chocolate', precoAdicional: 0 },
        ],
      },
      {
        nome: 'Tamanho',
        tipo: 'unica',
        obrigatorio: true,
        permiteQuantidade: false,
        opcoes: [
          { nome: '400 ml (padrão)', precoAdicional: 0 },
          { nome: '700 ml', precoAdicional: 8 },
        ],
      },
    ],
  },
  {
    nome: 'Cheesecake Oreo',
    categoria: 'Sobremesas',
    preco: 21.9,
    precoComDesconto: null,
    descricao: 'Cheesecake gelado com base e cobertura de Oreo.',
    imagem: 'oreochessecake.webp',
    disponivel: true,
  },
  {
    nome: 'Açaí',
    categoria: 'Sobremesas',
    preco: 19.9,
    precoComDesconto: null,
    descricao: 'Açaí cremoso. Escolha seu tamanho: 300 ml ou 500 ml.',
    imagem: 'açaí.webp',
    disponivel: true,
    tipo: 'com_acompanhamento',
    gruposOpcoes: [{
      nome: 'Tamanho',
      tipo: 'unica',
      obrigatorio: true,
      permiteQuantidade: false,
      opcoes: [
        { nome: '300 ml (padrão)', precoAdicional: 0 },
        { nome: '500 ml', precoAdicional: 6 },
      ],
    }],
  },
  {
    nome: 'Brigadeiro',
    categoria: 'Sobremesas',
    preco: 6,
    precoComDesconto: null,
    descricao: 'Brigadeiro tradicional de chocolate.',
    imagem: 'brigadeiro.webp',
    disponivel: true,
  },
  {
    nome: 'Brownie',
    categoria: 'Sobremesas',
    preco: 14.9,
    precoComDesconto: null,
    descricao: 'Brownie de chocolate com massa densa e macia.',
    imagem: 'brownie.webp',
    disponivel: true,
  },
];

module.exports = menuSeed.map(item => ({
  tipo: 'simples',
  gruposOpcoes: [],
  ...item,
}));
